name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
            - run: choco install netfx-4.8 wixtoolset
            - run: cargo install cargo-wix
            - run: cargo wix -v --nocapture
